Algoritmo "Pagamento"



Var

   nome : caractere
   valorHora, pagamento: real
   horas: inteiro


Inicio

   escreva("Nome: ")
   leia (nome)
   escreva ("Valor por hora: ")
   leia (valorHora)
   escreva("Horas trabalhadas: ")
   leia (horas)

   pagamento <- valorHora * horas)

   escreval
   escreval("Pagamento para ", nome, " Deve ser ", pagamento:8:2)



Fimalgoritmo